exclude: ^splicing/frontend/public/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        exclude: (?x)^.*\.md$
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-ast
        files: ^splicing/backend/

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
        files: ^splicing/backend/

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [
          "--multi-line", "3",
          "--trailing-comma",
          "--force-grid-wrap", "0",
          "--use-parentheses",
          "--ensure-newline-before-comments",
          "--line-length", "88",
          "--combine-as",
          "--project", "app",
        ]
        files: ^splicing/backend/

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--safe"]
        language_version: python3
        files: ^splicing/backend/

  - repo: https://github.com/pycqa/flake8.git
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-init-return==1.0.0
          - flake8-print
        args: ["--ignore=E501,B008,W503"]
        files: ^splicing/backend/

  - repo: local
    hooks:
      - id: frontend-lint
        name: Frontend Lint
        entry: bash -c 'cd splicing/frontend && npm run lint -- --fix'
        language: system
        files: ^splicing/frontend/
