name: Backend Test

on:
  pull_request:
    branches: '**'
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: |
        pip install poetry

    - name: Install dependencies
      run: |
        poetry install --with dev

    - name: Generate schema files
      run: |
        poetry run generate-schema

    - name: Run unit tests
      run: |
        cd splicing/backend
        PYTHONPATH=$PYTHONPATH:$(pwd) poetry run pytest tests
